usethis::use_build_ignore("dev_history.R")
usethis::use_gpl_license()
usethis::use_git("init pkg structure")
download.file("http://thinkr.fr/datasets.zip","inst/datasets.zip")
usethis::use_vignette("excel_files_from_zip")
usethis::use_package("dplyr")
usethis::use_package("purrr")
usethis::use_package("readxl")
usethis::use_package("utils")
usethis::use_package("magrittr")
devtools::build_vignettes()
pkgdown::build_site()
